export const identity = {
  name: "Pritam Biswas",
  handle: "pbs002-s",
  role: "App & Web Developer · AI Explorer · Competitive Programmer · Full-Stack Engineer",
  roles: [
    "App & Web Developer",
    "AI Explorer",
    "Competitive Programmer",
    "Full-Stack Developer",
    "Software Engineer",
  ],
  location: "Dhaka, Bangladesh",
  email: "pritam020s2@gmail.com",
  photo: "/photo.jpg",
  cvPdf: "/Pritam_Biswas_CV.pdf",
  motionReel: "/videos/motion-reel.mp4",
  education:
    "B.Tech in Computer Science & Engineering, Daffodil International University",
  educationDetail: "2nd Year | Class of 2028",
  availability: "Available for select roles / projects",
  bio: "Second-year CSE undergraduate shipping production-grade, distributed, and AI-integrated software solo end-to-end — from building an 11.3M PyTorch transformer and autonomous coding agent from scratch to multi-tenant campus platforms, multilingual support engines, and clinical EMG AI models.",
  profiles: {
    github: "https://github.com/pbs002-s",
    leetcode: "https://leetcode.com/u/Pritam_002/",
    codeforces: "https://codeforces.com/profile/Pritam-580",
    facebook: "https://www.facebook.com/pbs.020",
    instagram: "https://www.instagram.com/swagoto_pritom/",
    website: "https://pritam-biswas-portfolio.netlify.app",
  },
};

export const marqueeWords = [
  "React",
  "TypeScript",
  "Next.js",
  "Java 17",
  "Spring Boot",
  "Python",
  "PyTorch",
  "Kotlin",
  "Jetpack Compose",
  "PostGIS",
  "XGBoost",
  "Gemini",
  "GPT-4o",
  "Competitive Programming",
  "Docker",
  "FastAPI",
  "Redis",
  "PostgreSQL",
  "Node.js",
  "Laravel",
];

export const flatSkills = [
  {
    cat: "Core Languages & Tech",
    cmd: "stack --core",
    items: [
      "Python",
      "JavaScript",
      "TypeScript",
      "Java",
      "PHP",
      "React",
      "Node.js",
      "Express",
    ],
  },
  {
    cat: "Frameworks & Mobile",
    cmd: "stack --mobile",
    items: [
      "Kotlin",
      "Jetpack Compose",
      "Android",
      "Java 17",
      "Spring Boot",
      "Laravel",
      "Thymeleaf",
      "Maven",
      "Tailwind CSS",
      "HTML/CSS",
      "C",
    ],
  },
  {
    cat: "AI & Automation",
    cmd: "stack --ai",
    items: [
      "PyTorch",
      "From-Scratch LLM",
      "Autonomous Agent",
      "AST Indexing",
      "GPT-4o API",
      "Gemini API",
      "Gemini Vision",
      "Florence-2",
      "XGBoost",
      "Grad-CAM",
      "SHAP",
      "Groq / Llama 3.3",
    ],
  },
  {
    cat: "Engineering & Tools",
    cmd: "stack --tools",
    items: [
      "Git / GitHub",
      "Docker",
      "FastAPI",
      "WebSockets",
      "Socket.IO",
      "Redis",
      "PostgreSQL",
      "CRUD Architecture",
      "Role-Based Access",
      "REST APIs",
      "Room DB",
      "PostGIS",
      "Linux",
    ],
  },
];

export const metrics = [
  {
    value: "352+",
    label: "GitHub contributions",
    detail: "Past year verified",
  },
  {
    value: "23",
    label: "Stars earned",
    detail: "Community recognition",
  },
  {
    value: "14",
    label: "Repositories",
    detail: "Public & production",
  },
  {
    value: "100+",
    label: "Problems solved",
    detail: "LeetCode & Codeforces",
  },
];

export const projects = [
  {
    id: "ura-shree",
    name: "URA-Shree",
    subtitle: "From-Scratch Local LLM & Autonomous Coding Agent",
    status: "LIVE",
    openSource: true,
    year: "2026",
    stars: 5,
    commits: 24,
    role: "Solo Creator & AI Systems Architect",
    reel: "urashree",
    stack: [
      "Python",
      "PyTorch",
      "React 19",
      "TypeScript",
      "FastAPI",
      "WebSockets",
      "Docker",
    ],
    github: "https://github.com/pbs002-s/ura-shree-agent",
    details:
      "11.3M-param decoder-only transformer with RoPE, SwiGLU, GQA, and KV-cache. Custom byte-level BPE tokenizer (4096 tokens), AST workspace symbol indexer, persistent virtualenv shell, human-in-the-loop approval sandbox, and Time Machine snapshot rollbacks.",
    highlights: [
      "11.3M-param decoder-only transformer: RoPE, SwiGLU, GQA & KV-cache with lossless 4096-token byte-level BPE",
      "Autonomous agent loop & AST symbol indexing with zero-external-API local execution or multi-provider API seam",
      "Human-in-the-loop approval sandbox, persistent virtualenv shell, and content-addressed Time Machine workspace snapshots",
    ],
    category: "AI / AUTONOMOUS SYSTEMS",
    spec: "11.3M PARAMETERS",
    diagram: ["BYTE BPE", "TRANSFORMER", "AGENT"],
  },
  {
    id: "opengovtbd",
    name: "OpenGovtBD",
    subtitle: "Government–Citizen Civic Platform",
    status: "LIVE",
    openSource: true,
    year: "2025–2026",
    stars: 1,
    commits: 317,
    role: "Solo Creator",
    reel: "opengovtbd",
    stack: [
      "Java 17",
      "Spring Boot 3",
      "Thymeleaf",
      "Maven",
      "Chart.js",
      "REST APIs",
    ],
    github: "https://github.com/pbs002-s/OpenGovtBD",
    details:
      "Flagship 317-commit civic communications portal. Three role-based portals (Citizen, Officer, Super Admin) managing end-to-end complaint lifecycles, public discussions, official surveys, and transparent government service access.",
    highlights: [
      "Three role-based workspaces: Citizen, Officer, and Super Admin with strict audit trails",
      "Full complaint lifecycle & dynamic timeline tracking with resolution status workflows",
      "Gamified points, badges, citizen feedback analytics, and official public polling",
    ],
    category: "CIVIC / FULL-STACK",
    spec: "317 COMMITS · 3 PORTALS",
    diagram: ["CITIZEN", "LIFECYCLE", "OFFICER"],
  },
  {
    id: "edusync",
    name: "EduSync",
    subtitle: "Digital Campus Collaboration Platform",
    status: "LIVE",
    openSource: true,
    year: "2026",
    stars: 0,
    commits: 36,
    role: "Full-Stack Architect",
    reel: "edusync",
    stack: [
      "React 19",
      "TypeScript",
      "Laravel 13",
      "Node.js",
      "Socket.IO",
      "PostgreSQL",
      "Redis",
      "Docker",
    ],
    github: "https://github.com/pbs002-s/EduSync",
    details:
      "Multi-tenant digital university platform uniting 4 role-scoped portals (Student, Teacher, Admin, Authority). Real-time 1-on-1 and study group push messaging over Redis Pub/Sub, automated routine conflict detection, and academic grading queues.",
    highlights: [
      "4 role-scoped portals over a unified React 19 shell: Student, Teacher, Super Admin & Authority",
      "Real-time 1-on-1 & study group push messaging powered by Node.js, Socket.IO and Redis Pub/Sub",
      "Academic lifecycle engine with automated routine conflict detection, course enrollment & submission grading queues",
    ],
    category: "DISTRIBUTED / EDUCATION",
    spec: "4 ROLE-SCOPED PORTALS",
    diagram: ["PORTALS", "REDIS BUS", "SERVICES"],
  },
  {
    id: "bhoomisheba",
    name: "BhoomiSheba",
    subtitle: "Cadastral Automation Platform",
    status: "LIVE",
    openSource: true,
    year: "2026",
    stars: 0,
    commits: 36,
    role: "Solo Creator",
    reel: "bhoomisheba",
    stack: ["TypeScript", "React", "PostGIS", "Node.js", "Leaflet"],
    github: "https://github.com/pbs002-s/BhoomiSheba",
    details:
      "Next-gen Bangladesh land automation platform using PostGIS spatial GIS queries, e-mutation tracking workflows, multi-source cross-audits, and QR-verified e-Dakhila generation.",
    highlights: [
      "PostGIS spatial queries and Cadastral GIS polygon boundary validation",
      "e-Mutation tracking workflow with cross-department verification checkpoints",
      "Instant QR-verified e-Dakhila generation with cryptographic hash validation",
    ],
    category: "GEOSPATIAL / AUTOMATION",
    spec: "SPATIAL GIS · QR DAKHILA",
    diagram: ["LAND DATA", "POSTGIS", "QR VERIFY"],
  },
  {
    id: "bhashabot",
    name: "BhashaBot",
    subtitle: "Multilingual AI Messenger Agent",
    status: "LIVE",
    openSource: true,
    year: "2026",
    stars: 0,
    commits: 18,
    role: "Solo Creator",
    reel: "bhashabot",
    stack: [
      "TypeScript",
      "Next.js 14",
      "n8n",
      "GPT-4o",
      "Groq",
      "Llama 3.3",
      "libSQL",
    ],
    github: "https://github.com/pbs002-s/BhashaBot",
    details:
      "Automated Facebook Messenger support detecting 18 languages (including native Bangla/Banglish) using a single-webhook GPT-4o decision tree for reply generation, sentiment classification, lead extraction, and emergency human handoff.",
    highlights: [
      "Multilingual NLP auto-reply across 18 languages including native Bangla and Banglish",
      "One-webhook, one-decision-point architecture auto-routing refunds & emergencies to human agents",
      "Full lead extraction, sentiment analysis, and customer intent classification",
    ],
    category: "AI / CONVERSATIONAL",
    spec: "18 LANGUAGES SUPPORTED",
    diagram: ["WEBHOOK", "DECISION", "HANDOFF"],
  },
  {
    id: "diu-routine",
    name: "DIU Routine",
    subtitle: "Offline Android Class Scheduler",
    status: "LIVE",
    openSource: true,
    year: "2026",
    stars: 4,
    commits: 17,
    role: "Solo Creator",
    reel: "diuroutine",
    stack: [
      "Kotlin",
      "Jetpack Compose",
      "Android",
      "Gemini Vision",
      "Room DB",
    ],
    github: "https://github.com/pbs002-s/diu-routine",
    details:
      "Scans PDF/DOCX university schedules via Gemini Vision, auto-extracts timetable metadata, tracks attendance/streaks, and works 100% offline via Room Database.",
    highlights: [
      "Gemini Vision OCR extraction parsing complex university timetable layouts",
      "Room DB local persistence ensuring 100% offline access and fast launch",
      "Class attendance and streak tracking with automated daily reminders",
    ],
    category: "NATIVE / OFFLINE-FIRST",
    spec: "100% OFFLINE SCHEDULER",
    diagram: ["DOCUMENT", "VISION", "ROOM DB"],
  },
  {
    id: "khoroch-os",
    name: "khoroch-os",
    subtitle: "Tactile Personal Finance & Budget Engine",
    status: "LIVE",
    openSource: true,
    year: "2026",
    stars: 4,
    commits: 20,
    role: "Solo Creator",
    reel: "khoroch",
    stack: ["TypeScript", "React", "IndexedDB", "Tailwind CSS"],
    github: "https://github.com/pbs002-s/khoroch-os",
    details:
      "Zero-latency personal expenditure operating system. Offline-first ledger architecture using client-side IndexedDB, real-time category clustering, and CSV/JSON export.",
    highlights: [
      "Zero-latency client-side IndexedDB ledger architecture with instant sync",
      "Real-time category clustering and spending velocity insights",
      "Instant CSV & JSON data portability with tactile UI micro-interactions",
    ],
    category: "SYSTEMS / FINANCE",
    spec: "ZERO-LATENCY OFFLINE OS",
    diagram: ["LEDGER", "CLUSTER", "EXPORT"],
  },
  {
    id: "medical-llm",
    name: "medicalLLM",
    subtitle: "EMG ALS Screening Platform",
    status: "RESEARCH",
    openSource: true,
    year: "2026",
    stars: 1,
    commits: 4,
    role: "Solo Creator & Researcher",
    reel: "signal",
    stack: [
      "Python",
      "PyTorch",
      "Florence-2",
      "XGBoost",
      "Grad-CAM",
      "SHAP",
      "Gemini API",
      "React",
    ],
    github: "https://github.com/pbs002-s/medicalLLM",
    details:
      "End-to-end clinical neurophysiology platform screening for ALS from raw EMG waveforms. Fuses 1-D deep CNN waveforms with Florence-2 VLM spectrogram plots through an XGBoost meta-learner with 1-D Grad-CAM and Tree SHAP interpretability.",
    highlights: [
      "Multi-modal fusion: 1-D deep CNN on raw EMG + Florence-2 VLM on spectrogram plots",
      "XGBoost meta-learner reconciling waveform and visual signal features",
      "1-D Grad-CAM anomaly localization and Tree SHAP feature attribution",
    ],
    category: "RESEARCH / INTERPRETABLE AI",
    spec: "MULTIMODAL EMG AI",
    diagram: ["EMG + VLM", "XGBOOST", "EXPLAIN"],
  },
];

export const githubTelemetry = {
  username: "pbs002-s",
  contributionsTotal: 352,
  totalStars: 23,
  publicRepos: 13,
  languages: [
    { name: "TypeScript", percent: 49, color: "#3178c6" },
    { name: "Kotlin", percent: 40, color: "#A97BFF" },
    { name: "Python", percent: 6, color: "#3572A5" },
    { name: "Java", percent: 3, color: "#b07219" },
    { name: "HTML/CSS", percent: 2, color: "#e34c26" },
  ],
  repos: [
    {
      name: "OpenGovtBD",
      lang: "HTML/Java",
      langColor: "#b07219",
      commits: 317,
      stars: 1,
      category: "systems",
      desc: "Centralized Government–Citizen communications platform with 3 role portals, complaint resolution lifecycles, and public polling.",
      url: "https://github.com/pbs002-s/OpenGovtBD",
    },
    {
      name: "EduSync",
      lang: "TypeScript",
      langColor: "#3178c6",
      commits: 36,
      stars: 0,
      category: "systems",
      desc: "Multi-tenant digital campus collaboration platform: 4 role-scoped portals, real-time Socket.IO over Redis Pub/Sub.",
      url: "https://github.com/pbs002-s/EduSync",
    },
    {
      name: "BhoomiSheba",
      lang: "TypeScript",
      langColor: "#3178c6",
      commits: 36,
      stars: 0,
      category: "systems",
      desc: "Cadastral automation platform with PostGIS spatial GIS, e-mutation tracking, and QR e-Dakhila generation.",
      url: "https://github.com/pbs002-s/BhoomiSheba",
    },
    {
      name: "LeetCode",
      lang: "Java",
      langColor: "#b07219",
      commits: 52,
      stars: 2,
      category: "algorithms",
      desc: "50+ optimized algorithmic implementations across dynamic programming, graph traversal, and bit manipulation.",
      url: "https://github.com/pbs002-s/LeetCode",
    },
    {
      name: "khoroch-os",
      lang: "TypeScript",
      langColor: "#3178c6",
      commits: 20,
      stars: 4,
      category: "apps",
      desc: "Tactile personal finance ledger OS running entirely on client-side IndexedDB with reactive balance analytics.",
      url: "https://github.com/pbs002-s/khoroch-os",
    },
    {
      name: "diu-routine",
      lang: "Kotlin",
      langColor: "#A97BFF",
      commits: 17,
      stars: 4,
      category: "apps",
      desc: "Offline Android class scheduler with Gemini Vision schedule parsing and Room DB local cache.",
      url: "https://github.com/pbs002-s/diu-routine",
    },
    {
      name: "BhashaBot",
      lang: "TypeScript",
      langColor: "#3178c6",
      commits: 18,
      stars: 0,
      category: "ai",
      desc: "Multi-channel AI reply engine parsing 18 languages using single-webhook GPT-4o decision routing.",
      url: "https://github.com/pbs002-s/BhashaBot",
    },
    {
      name: "medicalLLM",
      lang: "Python",
      langColor: "#3572A5",
      commits: 4,
      stars: 1,
      category: "ai",
      desc: "Multimodal clinical EMG waveform ALS screening platform fusing 1-D CNNs with Florence-2 VLMs and Tree SHAP.",
      url: "https://github.com/pbs002-s/medicalLLM",
    },
  ],
};

export const skillGroups = [
  {
    id: "core",
    label: "Core Languages",
    short: "CORE",
    domain: "Engineering foundations",
    description:
      "The language layer underneath algorithms, interfaces, and production systems.",
    position: [-1.7, 0.85, 0],
    skills: [
      "Python",
      "JavaScript",
      "TypeScript",
      "Java 17",
      "Kotlin",
      "C",
      "PHP",
      "SQL",
    ],
  },
  {
    id: "frontend",
    label: "Frontend & Mobile",
    short: "INTERFACES",
    domain: "Full-Stack Web + Native Mobile",
    description:
      "Responsive web interfaces and native Android experiences, including offline-first applications.",
    position: [1.55, 1.05, -0.3],
    skills: [
      "React 19",
      "Next.js 14",
      "Jetpack Compose",
      "Tailwind CSS",
      "HTML5/CSS3",
    ],
  },
  {
    id: "backend",
    label: "Backend & Distributed",
    short: "SYSTEMS",
    domain: "Distributed Systems",
    description:
      "Role-scoped platforms, real-time messaging, spatial data, and persistent service infrastructure.",
    position: [1.7, -1.05, 0.3],
    skills: [
      "Node.js",
      "Express",
      "Spring Boot 3",
      "Laravel 13",
      "FastAPI",
      "WebSockets",
      "Socket.IO",
      "Redis",
      "PostgreSQL",
      "Room DB",
      "PostGIS",
    ],
  },
  {
    id: "ai",
    label: "AI & Systems",
    short: "INTELLIGENCE",
    domain: "AI Systems",
    description:
      "From transformer internals and autonomous agents to interpretable multimodal research.",
    position: [-1.45, -1.05, -0.25],
    skills: [
      "PyTorch",
      "From-Scratch LLM",
      "Transformer Architecture",
      "Autonomous Agents",
      "AST Indexing",
      "Florence-2",
      "XGBoost",
      "Grad-CAM",
      "SHAP",
      "Gemini Vision",
      "GPT-4o API",
      "Docker",
      "Git",
      "Linux",
    ],
  },
];

export const experience = [
  {
    period: "2024 — Present",
    title: "Independent Product Engineer",
    detail: "Architected & deployed 8+ full-stack & AI projects solo.",
    type: "EXPERIENCE",
  },
  {
    period: "2024 — Present",
    title: "Competitive Programmer",
    detail: "Active competitor on LeetCode & Codeforces (50+ solutions tracked).",
    type: "PRACTICE",
  },
];

export const honors = [
  "1st Place Institutional Science Fair (3 consecutive years)",
  "Government of Bangladesh Recognition (National Science Fair & Digital Bangladesh)",
];

export const socials = [
  { label: "GitHub", mark: "GH", href: identity.profiles.github },
  { label: "LeetCode", mark: "LC", href: identity.profiles.leetcode },
  { label: "Codeforces", mark: "CF", href: identity.profiles.codeforces },
  { label: "Facebook", mark: "FB", href: identity.profiles.facebook },
  { label: "Instagram", mark: "IG", href: identity.profiles.instagram },
];